### ISSUE TITLE
How to run LDpred2-auto

### ISSUE THREAD

**Issue by privefl** [GRealesM/RapidoPGS_paper#1]
Congrats on your new preprint. I've been reading it with much interest.

A few remarks on how to run LDpred2-auto.

1/ 
> Note that LDpred2-auto uses SNP thinning to limit computational burden, and we found that we could not raise the thinning parameter above 10% (i.e. discard 90% of SNPs at random) without segfault errors, thus all are comparisons are against this setting.

What does that mean? I'm not doing any filtering in LDpred2.

2/ 
Seems you're running LDpred2-auto with only one initial value for `p` (which means that argument `ncores` is useless here). I recommend that you use at least 15 or 30 as recommend in the code (please see https://github.com/privefl/paper-ldpred2/blob/master/code/run-ldpred2.R#L101-L108). If you use 15 cores, then it will take the same time (or twice as much for 30 initial values).

**Comment by GRealesM** [comment]
Thanks a lot for your feedback, Florian, it is really encouraging to hear from you.
We were as careful as we could to generate PGS following both methods and make fair comparisons between them,
but of course we might have made mistakes, so having your input is really useful to us!
Regarding your first question, we followed the LDpred2 vignette as closely as possible, excluding the prediction part using invidual data.
One of the first steps is to generate a reference panel from 1000 genomes Phase I, to be used by LDpred2 (https://github.com/privefl/bigsnpr/blob/master/data-raw/public-data.R), at this point, you use Plink to extract chromosomes 2,6, and 8 for your example, and use --thin 0.1 flag, which filters SNPs at random, using a probability of 0.1 to be selected. Later, in the vignette, you suggest to perform PGS generation chromsome by chromosome and then append results, so we did the plink step on a chr-by-chr basis, including --thin 0.1 flag.
We noticed that this would greatly reduce the amount of SNPs available for PGS computation in LDpred2, and possibly undermine LDpred2 performance, so we tried to re-create our reference panel using different thinning parameters {0.2,0.3,..., no thinning}. However, when running LDpred2 using reference data thinned above 0.1, we run into segfault errors like that described [here](https://github.com/privefl/bigsnpr/issues/96).
We tried with different combinations of cores (in our CentOS 7 HPC), as someone suggested reducing cores as a possible solution elsewhere, but to no avail. Thus, we ended up using 0.1 thinned reference only. We may however retry in the future, if we find a solution for that.
Regarding your second question, I recall that we used a set of ~10 init_p values in our initial tests, but we observed that the resulting beta columns were not very different among them, and so taking a mean wouldn't change the outcome too much, and would probably take longer to run. We were not aware though that using multiple cores serves precisely for that purpose. Thus, we used 1e-4 as init_p only, because that's the same prior value that we used in RápidoPGS, which has been shown to be a reasonable prior value.

We hope we have addressed your concerns properly. Thank you again for your valuable feedback, and we'd be happy to hear more from you, if you have additional comments.

**Comment by privefl** [comment]
- Ok, I understand now. But, the data thinned from the 1000G is just some "fake" data that I use in all tutorials for educational purposes. We recommend to use HM3 variants in the tutorial (see the end). I will specify that this 1000G data is for educational purpose only, sorry for the confusion.

- Averaging models is always better :'). And it allows some "check" that all models went smoothly.

- Also, the quality control recommended in the paper was particularly beneficial for LDpred2-auto. Are you performing it?

**Comment by GRealesM** [comment]
I see! Thanks for pointing that out. I'll redo LDpred2-auto models following your advice. 
We also displayed the results in your paper alongside with our "thinned" ones, to avoid letting possible mistakes in our own run of LDpred2-auto mislead anyone, so thank you as well for making your full results available in your paper!

**Comment by privefl** [comment]
A few comments on the way you run LDpred2 in the second version of the preprint:
- Again, you do not use the recommended QC on sumstats; you say you cannot compute SDval but you do have individual-level data to compute AUCs, or you could just use SDval ~ sqrt(2*p*(1-p)).
- You use a very small LD ref panel, while we provide a larger one
- You run LDpred2-auto per chromosome
- You average betas from all 15 chains without checking divergence, which means that if any of them gone wrong, the average would be bad

**Comment by GRealesM** [comment]
Dear Florian,
I hope you’re doing well. Thank you for your reading of our paper and your comments. Let me address them:

(1) On QC: Indeed, we explain in the paper that we don’t remove SNPs based on SDval. Our approach assumes that the user may not have individual-level data, and that’s ok regarding model generation using RápidoPGS, as it does not require information from the individuals, and we use these individual-level data just for the purpose of evaluating the methods. I understand that LDpred2 benefits from filtering by SDval, but we wanted to keep our implementations of the methods as similar as possible. How much do you think the lack of this particular QC filter may affect results in the LDpred2 case?
(2) On LD ref panel: We decided to use 1000 Genomes project, which as we admit in the paper, is small, although it has the nice feature of being open access to everyone, and we provide a function to download and prepare it for use with minimal effort on the user side. I think using your UKBB LD matrices may well improve results for both RápidoPGS-multi and LDpred2, but we wanted to make a tool available for everyone using open-access data, and applicable across different ancestries.
(3) LDpred2 per-chr vs. LDpred2gwide: We still run LDpred2 per-chr instead of genomewide as we found even per-chromosome was fairly heavy on the memory side on our cluster, while differences in performance for most traits in the LDpred2 paper don’t seem so big. It would be interesting to know if the genome-wide approach is faster, but from my reading of the paper, I didn’t think this would be the case.
(4) Chain divergence: I set all chains to run for 4000 iterations (1000 burn-in + 3000), which is 6 times more non-burn-in iterations than the LDpred2 default. I checked for convergence in early tests on some datasets and chromosomes and this seemed enough to ensure convergence in most cases. We could have used the method in the tutorial to automatically remove bad chains based on prediction results, but again this would imply “borrowing” information from the validation dataset at PGS generation step.

In any case, and as we did in the previous version, we show AUC results for the same datasets in LDpred2 paper (LDpred2-auto, genome-wide approach) in Figure 1, so readers can assess the differences between both LDpred2 runs.

**Comment by privefl** [comment]
(1) You can always use SDval ~ sqrt(2p(1-p)) without needing individual-level data (which you have). The QC is very important, and particularly in the UK Biobank where it is suspected there are errors in the genotypes.

(2) LDpred1 recommend not using any LD ref with less than 2000 individuals. We have not really re-investigated this in LDpred2 though.

(3) On chromosome 1 only, the memory footprint of LDpred2 should be something like 4GB (and 40GB if run gwide), I'm very surprised by this "heavy memory".

(4) You could increase the number of burn-in iterations to ensure that the Gibbs sampler achieve a stable state (but the default 1000 is already more than enough for most cases). But increasing the number of iterations (that are all averaged as part of the result) is just increasing the probability of it diverging. You can always use the QC on chains in the test set since it does not use the phenotype information.

**Comment by GRealesM** [comment]
Florian, thank you for the clear advice, which I will definitely use next time I run LDPred2.  For now, I hope by providing your gold standard PGS scores next to ours, readers can compare our RápidoPGS to your LDPred2 results, noting that ours is only intended to be a fast approximation rather than a more accurate method.
